services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - "${SOLSTICE_GATEWAY_PORT:-4000}:${SOLSTICE_GATEWAY_PORT:-4000}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SOLSTICE_GATEWAY_PORT=${SOLSTICE_GATEWAY_PORT:-4000}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src  # hot reload for development
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  # Add your citation-finder app here later
  # citation-finder:
  #   build: ./apps/citation-finder
  #   environment:
  #     - LLM_GATEWAY_URL=http://gateway:4000
  #   depends_on:
  #     - gateway
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
