services:
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - "${SOLSTICE_GATEWAY_PORT:-8000}:${SOLSTICE_GATEWAY_PORT:-8000}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SOLSTICE_GATEWAY_PORT=${SOLSTICE_GATEWAY_PORT:-8000}
      - SOLSTICE_LOG_LEVEL=${SOLSTICE_LOG_LEVEL:-INFO}
    volumes:
      - ./src:/app/src  # hot reload for development
    networks:
      - app-network
    restart: unless-stopped

  # Add your citation-finder app here later
  # citation-finder:
  #   build: ./apps/citation-finder
  #   environment:
  #     - LLM_GATEWAY_URL=http://gateway:8000
  #   depends_on:
  #     - gateway
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
